name: staging

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: setup ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install packages
        run: npm ci #using package-lock

      # testing
      # - name: run tests
      #   run: npm test

      # deployment      
      - name: deploy
        run: npm i -g @railway/cli && railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
        if: github.event_name == 'push'