name: staging

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [16, 18]

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: setup ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install packages
        run: npm ci #using package-lock

      # testing
      - name: run tests
        run: npm test
        env:
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: postgres
          POSTGRES_PORT: 5432
          POSTRGRES_HOST: localhost

      # deployment
      - name: deploy
        run: npm i -g @railway/cli && railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
        if: github.event_name == 'push'   
